import React, { useState, useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { ArrowLeft, Download, Sparkles, Loader2 } from 'lucide-react';
import { motion } from 'framer-motion';
import { base44 } from '@/api/base44Client';

const TRANSLATIONS = [
  { legacy: 'Managed a classroom', tech: 'Coordinated daily operations and stakeholder engagement.' },
  { legacy: 'Developed curriculum', tech: 'Architected scalable content frameworks.' },
  { legacy: 'Assessed student progress', tech: 'Analyzed user performance metrics to iterate on strategy.' },
];

export default function HorizonSynthesis() {
  const location = useLocation();
  const auditAnswers = location.state?.answers || {};

  const [loading, setLoading] = useState(false);
  const [synthesis, setSynthesis] = useState(null);

  useEffect(() => {
    generateSynthesis();
  }, []);

  const generateSynthesis = async () => {
    setLoading(true);

    const auditText = Object.keys(auditAnswers).length
      ? Object.entries(auditAnswers)
          .map(([k, v]) => `Q${k}: ${v}`)
          .join('\n')
      : 'No audit answers provided yet.';

    const translationText = TRANSLATIONS.map(t => `"${t.legacy}" → "${t.tech}"`).join('\n');

    const prompt = `You are the Hearth & Horizon career transition guide for public-sector professionals moving into tech/corporate roles.

Based on the following Horizon Audit responses and Identity Translations, produce:
1. A warm, encouraging "Summary of Journey" paragraph (3-4 sentences) that honours their public-sector history and frames their transition positively.
2. A concrete "90-Day Action Plan" with exactly 3 phases (Days 1-30, Days 31-60, Days 61-90), each with 2-3 specific, actionable steps tailored to their answers.

Horizon Audit Answers:
${auditText}

Identity Translations used:
${translationText}

Respond in JSON format like:
{
  "summary": "...",
  "plan": [
    { "phase": "Days 1–30", "title": "Root & Reflect", "steps": ["...", "..."] },
    { "phase": "Days 31–60", "title": "Translate & Build", "steps": ["...", "..."] },
    { "phase": "Days 61–90", "title": "Bridge & Launch", "steps": ["...", "..."] }
  ]
}`;

    const result = await base44.integrations.Core.InvokeLLM({
      prompt,
      response_json_schema: {
        type: 'object',
        properties: {
          summary: { type: 'string' },
          plan: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                phase: { type: 'string' },
                title: { type: 'string' },
                steps: { type: 'array', items: { type: 'string' } },
              },
            },
          },
        },
      },
    });

    setSynthesis(result);
    setLoading(false);
  };

  const handleDownload = () => {
    if (!synthesis) return;
    const lines = [
      '✦ HEARTH & HORIZON — 90-DAY ACTION PLAN ✦',
      '',
      'SUMMARY OF YOUR JOURNEY',
      '─────────────────────────────────',
      synthesis.summary,
      '',
      '90-DAY ACTION PLAN',
      '─────────────────────────────────',
      ...synthesis.plan.flatMap(p => [
        '',
        `${p.phase}: ${p.title}`,
        ...p.steps.map(s => `  • ${s}`),
      ]),
      '',
      '─────────────────────────────────',
      'Generated by Hearth & Horizon',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'Hearth-Horizon-90-Day-Plan.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      className="min-h-screen px-4 py-10"
      style={{
        background: `linear-gradient(135deg, hsl(280, 25%, 11%) 0%, hsl(183, 35%, 14%) 60%, hsl(35, 40%, 13%) 100%)`,
      }}
    >
      <div className="max-w-2xl mx-auto space-y-8">
        {/* Back */}
        <Button asChild variant="ghost" size="sm" className="text-muted-foreground hover:text-foreground gap-2">
          <Link to="/guide">
            <ArrowLeft className="w-4 h-4" />
            Back to Forest Guide
          </Link>
        </Button>

        {/* Header */}
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="space-y-2">
          <h1 className="font-heading text-4xl font-bold text-foreground">✦ Horizon Synthesis</h1>
          <p className="text-muted-foreground text-base leading-relaxed">
            Your journey, distilled. Below is your personalised summary and 90-day roadmap generated by the Hearth's logic.
          </p>
        </motion.div>

        {/* Loading */}
        {loading && (
          <motion.div
            initial={{ opacity: 0 }} animate={{ opacity: 1 }}
            className="rounded-2xl border border-white/10 p-12 flex flex-col items-center gap-4 shadow-2xl backdrop-blur-sm"
            style={{ background: 'hsla(280, 25%, 12%, 0.82)' }}
          >
            <Loader2 className="w-10 h-10 text-amber-400 animate-spin" />
            <p className="text-muted-foreground text-sm">The Hearth is reading the forest leaves…</p>
          </motion.div>
        )}

        {/* Results */}
        {synthesis && !loading && (
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="space-y-6">

            {/* Summary */}
            <div
              className="rounded-2xl border border-white/10 p-6 space-y-3 shadow-2xl backdrop-blur-sm"
              style={{ background: 'hsla(280, 25%, 12%, 0.82)' }}
            >
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-amber-400" />
                <h2 className="font-heading text-lg font-semibold text-foreground">Summary of Your Journey</h2>
              </div>
              <p className="text-sm text-foreground/85 leading-relaxed">{synthesis.summary}</p>
            </div>

            {/* 90-Day Plan */}
            <div
              className="rounded-2xl border border-white/10 overflow-hidden shadow-2xl backdrop-blur-sm"
              style={{ background: 'hsla(280, 25%, 12%, 0.82)' }}
            >
              <div className="px-6 py-4 border-b border-white/10 flex items-center gap-2">
                <h2 className="font-heading text-lg font-semibold text-foreground">Your 90-Day Action Plan</h2>
              </div>
              <div className="divide-y divide-white/5">
                {synthesis.plan.map((phase, i) => (
                  <div key={i} className="px-6 py-5 space-y-3">
                    <div className="flex items-baseline gap-3">
                      <span className="text-xs font-mono text-amber-400/80 tracking-widest">{phase.phase}</span>
                      <span className="font-heading font-semibold text-foreground">{phase.title}</span>
                    </div>
                    <ul className="space-y-2">
                      {phase.steps.map((step, j) => (
                        <li key={j} className="flex items-start gap-2 text-sm text-foreground/80">
                          <span className="text-amber-400 mt-0.5 shrink-0">•</span>
                          {step}
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            </div>

            {/* Download */}
            <Button
              onClick={handleDownload}
              className="w-full h-11 bg-amber-500 hover:bg-amber-400 text-background font-semibold gap-2"
            >
              <Download className="w-4 h-4" />
              Download My 90-Day Plan
            </Button>
          </motion.div>
        )}
      </div>
    </div>
  );
}